### ISSUE TITLE
Dies when exposed to bright images

### ISSUE THREAD

**Issue by skylatian** [d4rken/fpv-dvca#1]
It works completely fine at first-sub 1/2sec latency-then when I point it at a lamp it suddenly starts to stutter to around 1 frame/second or worse with obviously high latency. Any ideas about what's going on? Thinking it might be something about compression over USB and a large image change forcing more data to change? also could be talking out of my ass, no idea what's going on.

**Comment by d4rken** [comment]
Sounds like a device decoding issue.
Which Goggle, device and app version?

**Comment by d4rken** [comment]
Tried shining a light into the camera and while there were a few frames dropped, the feed was still okay on a Pixel 5.

**Comment by ATKCA** [comment]
This same issue is on Digiview too. Some systems even PC's experience slow down. It happens worse if the room is dark and you point at the light.

**Comment by d4rken** [comment]
Not much I can act on here, for now just report after each new version.
Lots of learning and improving happening  :slightly_smiling_face: .

**Comment by skylatian** [comment]
Sorry, didn't see this earlier - Android 5.0, V1 goggles on a Note 3 (AT&T Exynos), app version v0.0.5

**Comment by skylatian** [comment]
Updating with the new app version - buffered_blocking seems to recover best from the light issue, but the issue still occurs. Happy to test anything if you need it!

**Comment by d4rken** [comment]
@skylatian  How does the latest version work for you? 0.1.3?

**Comment by skylatian** [comment]
late update, got busy - new behavior is much much better, issue still occurs but recovery is almost instant after light source is removed. Also a lot less touchy. Effect worsens as my vista heats up, so keep that in mind when testing! https://imgur.com/a/9Os7o8F

**Comment by d4rken** [comment]
Closing as there is not much that I can do here.
